# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snake.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'snake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsnake.proto\x12\tsnakegame\"\x07\n\x05\x45mpty\" \n\x0bMoveRequest\x12\x11\n\tdirection\x18\x01 \x01(\t\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"|\n\tGameState\x12\'\n\nsnake_body\x18\x01 \x03(\x0b\x32\x13.snakegame.Position\x12!\n\x04\x66ood\x18\x02 \x01(\x0b\x32\x13.snakegame.Position\x12\r\n\x05score\x18\x03 \x01(\x05\x12\x14\n\x0cis_game_over\x18\x04 \x01(\x08\x32\x83\x01\n\x0cSnakeService\x12<\n\nUpdateGame\x12\x16.snakegame.MoveRequest\x1a\x14.snakegame.GameState\"\x00\x12\x35\n\tResetGame\x12\x10.snakegame.Empty\x1a\x14.snakegame.GameState\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_MOVEREQUEST']._serialized_start=35
  _globals['_MOVEREQUEST']._serialized_end=67
  _globals['_POSITION']._serialized_start=69
  _globals['_POSITION']._serialized_end=101
  _globals['_GAMESTATE']._serialized_start=103
  _globals['_GAMESTATE']._serialized_end=227
  _globals['_SNAKESERVICE']._serialized_start=230
  _globals['_SNAKESERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
