# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import snake_pb2 as snake__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in snake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SnakeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateGame = channel.unary_unary(
                '/snakegame.SnakeService/UpdateGame',
                request_serializer=snake__pb2.MoveRequest.SerializeToString,
                response_deserializer=snake__pb2.GameState.FromString,
                _registered_method=True)
        self.ResetGame = channel.unary_unary(
                '/snakegame.SnakeService/ResetGame',
                request_serializer=snake__pb2.Empty.SerializeToString,
                response_deserializer=snake__pb2.GameState.FromString,
                _registered_method=True)


class SnakeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnakeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGame,
                    request_deserializer=snake__pb2.MoveRequest.FromString,
                    response_serializer=snake__pb2.GameState.SerializeToString,
            ),
            'ResetGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetGame,
                    request_deserializer=snake__pb2.Empty.FromString,
                    response_serializer=snake__pb2.GameState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snakegame.SnakeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snakegame.SnakeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnakeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snakegame.SnakeService/UpdateGame',
            snake__pb2.MoveRequest.SerializeToString,
            snake__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snakegame.SnakeService/ResetGame',
            snake__pb2.Empty.SerializeToString,
            snake__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
